langauge: node_js
node_js:
    - "12"
    - "13"

install:
    - npm install

script:
    - npm run test-ci

after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
